apiVersion: v1
kind: ServiceAccount
metadata:
  name: notifier-svc-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: notifier-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notifier-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: notifier-svc-account
  namespace: default
roleRef:
  kind: Role
  name: notifier-role
  apiGroup: rbac.authorization.k8s.io