apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-notifier
spec: 
  selector: 
    app: {{ .Release.Name }}-notifier
  ports: 
    - protocol: TCP 
      port: 3002 
      targetPort: 3002
