#Container Image Specification
image:
  repository: repository 
  tag: tag
  pullPolicy: Always

#Container Environment Specifications
env:
  dbusername: dbuser
  dbpassword: dbpassword
  dbname: dbname
  dbhost: dbhost
  broker1: broker1
  broker2: broker2
  broker3: broker3

#Deployment Specification
deployment:
  strategy: RollingUpdate
  strategyKey: rollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  minReadySeconds: 30
  progressDeadlineSeconds: 35

#Probe Specifications
probe:
  liveness:
    initialDelay: 50
    periodSeconds: 30   
  readiness:
    initialDelay: 50

#Autoscaling Configuration
scaling:
  maxCPUUtilizationPercent: 70
  cpuMillicore: 100m